- name: Uninstall old versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Update apt and install docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  become: true

- name: Create the docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: true
    state: present
  become: true
  notify: reset connection

- name: Make sure docker service is running
  ansible.builtin.systemd:
    state: started
    name: docker
