- name: Add Google Cloud public signing key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Add the Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  become: true

- name: Update apt and install kubectl
  ansible.builtin.apt:
    name: "{{ kubectl_pkg }}"
    state: present
    update_cache: true
  become: true

- name: Enable autocompletion for kubectl
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: source <(kubectl completion bash)
    state: present
