- name: Add Terraform GPG apt Key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Find the distribution release codename for your current system
  ansible.builtin.shell: echo $(lsb_release -cs)
  register: lsb_release
  changed_when: false

- name: Add Terraform Repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main
    state: present
  become: true

- name: Update apt and install Terraform
  ansible.builtin.apt:
    name: "{{ terraform_pkg }}"
    state: present
    update_cache: true
  become: true
  notify: terraform_autocomplete
